
services:
    hoborg.identity:
        class: Hoborg\Bundle\CommonsBundle\Service\Identity
        arguments:
            - @cmns_mapper_factory

#    cmns_api_factory:
#        arguments:
#            - @cmns_mapper_factory

    cmns_mapper_factory:
        class: Hoborg\Bundle\CommonsBundle\Mapper\Factory
        arguments:
            - @doctrine
